/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annotationviewer;

import java.awt.Component;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayyzz
 */
public class Gui extends javax.swing.JFrame {
    String filename = "";
    
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SequenceInfo = new javax.swing.JTextField();
        GeneView = new javax.swing.JScrollPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        SequenceView = new javax.swing.JScrollPane();
        FeatureView = new javax.swing.JScrollPane();
        FeatureShow = new javax.swing.JLabel();
        HelpButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        ItemOpen = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        Print = new javax.swing.JMenuItem();
        PrintPreview = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        SelectedFeatures = new javax.swing.JMenuItem();
        Overview = new javax.swing.JMenuItem();
        ForwardStrandOverview = new javax.swing.JMenuItem();
        ReverseStrandOverview = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenu();
        Organism = new javax.swing.JMenuItem();
        Domein = new javax.swing.JMenuItem();
        Feature = new javax.swing.JMenuItem();
        CelType = new javax.swing.JMenuItem();
        Blast = new javax.swing.JMenu();
        NCBIsearches = new javax.swing.JMenu();
        blastP = new javax.swing.JMenuItem();
        blastN = new javax.swing.JMenuItem();
        TblastN = new javax.swing.JMenuItem();
        blastX = new javax.swing.JMenuItem();
        TblastX = new javax.swing.JMenuItem();
        Graph = new javax.swing.JMenu();
        gcPercentage = new javax.swing.JMenuItem();
        agPercentage = new javax.swing.JMenuItem();
        gcFramePlot = new javax.swing.JMenuItem();
        CorralationScores = new javax.swing.JMenuItem();
        Export = new javax.swing.JMenu();
        ExportTo = new javax.swing.JMenu();
        FASTA = new javax.swing.JMenuItem();
        GFF = new javax.swing.JMenuItem();
        Genbank = new javax.swing.JMenuItem();
        DNA = new javax.swing.JMenuItem();
        AminoAcids = new javax.swing.JMenuItem();
        Features = new javax.swing.JMenuItem();
        CDS = new javax.swing.JMenuItem();
        ORF = new javax.swing.JMenuItem();
        SelectedFeature = new javax.swing.JMenuItem();
        SelectedSequence = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        AddGene = new javax.swing.JMenuItem();
        EditSelectedFeature = new javax.swing.JMenuItem();
        ExtendsSelectedFeature = new javax.swing.JMenu();
        ToPreviousStopCodon = new javax.swing.JMenuItem();
        ToNextStopCodon = new javax.swing.JMenuItem();
        HeaderOfDefaultEntry = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GeneView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        GeneView.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jCheckBox1.setText("ORF");

        jCheckBox2.setText("Stop Codons");

        jCheckBox3.setText("Protein");

        jCheckBox4.setText("DNA");

        jCheckBox5.setText("Gene");

        SequenceView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        SequenceView.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        FeatureView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        FeatureView.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        FeatureShow.setText("Features");

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        File.setText("File");

        ItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        ItemOpen.setText("Open");
        ItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemOpenActionPerformed(evt);
            }
        });
        File.add(ItemOpen);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setText("Save");
        File.add(Save);

        SaveAs.setText("Save As");
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        File.add(SaveAs);

        Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Print.setText("Print");
        File.add(Print);

        PrintPreview.setText("Print Preview");
        File.add(PrintPreview);

        jMenuBar1.add(File);

        View.setText("View");

        SelectedFeatures.setText("Selected Features");
        View.add(SelectedFeatures);

        Overview.setText("Overview");
        View.add(Overview);

        ForwardStrandOverview.setText("Forward Strand Overview");
        ForwardStrandOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardStrandOverviewActionPerformed(evt);
            }
        });
        View.add(ForwardStrandOverview);

        ReverseStrandOverview.setText("Reverse Strand Overview");
        View.add(ReverseStrandOverview);

        jMenuBar1.add(View);

        Search.setText("Search");

        Organism.setText("Organism");
        Search.add(Organism);

        Domein.setText("Domein");
        Search.add(Domein);

        Feature.setText("Feature");
        Search.add(Feature);

        CelType.setText("Cel type");
        CelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelTypeActionPerformed(evt);
            }
        });
        Search.add(CelType);

        jMenuBar1.add(Search);

        Blast.setText("BLAST");

        NCBIsearches.setText("NCBI Searches");

        blastP.setText("blastP");
        blastP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastPActionPerformed(evt);
            }
        });
        NCBIsearches.add(blastP);

        blastN.setText("blastN");
        blastN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastNActionPerformed(evt);
            }
        });
        NCBIsearches.add(blastN);

        TblastN.setText("TblastN");
        NCBIsearches.add(TblastN);

        blastX.setText("blastX");
        NCBIsearches.add(blastX);

        TblastX.setText("TblastX");
        NCBIsearches.add(TblastX);

        Blast.add(NCBIsearches);

        jMenuBar1.add(Blast);

        Graph.setText("Graph");

        gcPercentage.setText("GC Content (%)");
        Graph.add(gcPercentage);

        agPercentage.setText("AG Content (%)");
        Graph.add(agPercentage);

        gcFramePlot.setText("GC Frame Plot");
        Graph.add(gcFramePlot);

        CorralationScores.setText("Correlation Scores");
        Graph.add(CorralationScores);

        jMenuBar1.add(Graph);

        Export.setText("Export");

        ExportTo.setText("Export To");

        FASTA.setText("FASTA");
        ExportTo.add(FASTA);

        GFF.setText("GFF");
        ExportTo.add(GFF);

        Genbank.setText("Genbank");
        ExportTo.add(Genbank);

        Export.add(ExportTo);

        DNA.setText("DNA");
        Export.add(DNA);

        AminoAcids.setText("Amino Acids");
        Export.add(AminoAcids);

        Features.setText("Features");
        Export.add(Features);

        CDS.setText("CDS");
        Export.add(CDS);

        ORF.setText("ORF's");
        Export.add(ORF);

        SelectedFeature.setText("Selected Feature");
        Export.add(SelectedFeature);

        SelectedSequence.setText("Selected Sequence");
        SelectedSequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedSequenceActionPerformed(evt);
            }
        });
        Export.add(SelectedSequence);

        jMenuBar1.add(Export);

        Edit.setText("Edit");

        Undo.setText("Undo");
        Edit.add(Undo);

        Redo.setText("Redo");
        Edit.add(Redo);

        AddGene.setText("Add Gene");
        AddGene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGeneActionPerformed(evt);
            }
        });
        Edit.add(AddGene);

        EditSelectedFeature.setText("Selected Feature (s)");
        Edit.add(EditSelectedFeature);

        ExtendsSelectedFeature.setText("Extend Selected Feature");

        ToPreviousStopCodon.setText("To Previous Stop Codon");
        ExtendsSelectedFeature.add(ToPreviousStopCodon);

        ToNextStopCodon.setText("To Next Stop Codon");
        ToNextStopCodon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToNextStopCodonActionPerformed(evt);
            }
        });
        ExtendsSelectedFeature.add(ToNextStopCodon);

        Edit.add(ExtendsSelectedFeature);

        HeaderOfDefaultEntry.setText("Header Of Default Entry");
        Edit.add(HeaderOfDefaultEntry);

        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeatureView, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SequenceView, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SequenceInfo)
                    .addComponent(GeneView)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox2))
                            .addComponent(FeatureShow))
                        .addGap(0, 954, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HelpButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HelpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SequenceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GeneView, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(SequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FeatureShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FeatureView, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveAsActionPerformed

    private void CelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelTypeActionPerformed

    private void ForwardStrandOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardStrandOverviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForwardStrandOverviewActionPerformed

    private void SelectedSequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedSequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedSequenceActionPerformed

    private void ToNextStopCodonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToNextStopCodonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToNextStopCodonActionPerformed

    private void AddGeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGeneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGeneActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        Component frame = null;
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(frame,
    "This is a help button."
            + "\n" +"Go read the fucking manual");
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void ItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        AV av = new AV();
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(Gui.this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            filename = (c.getCurrentDirectory().toString() + "\\" + c.getSelectedFile().getName());
            System.out.println(filename);
            av.makeArrayList(filename);
        }
    }//GEN-LAST:event_ItemOpenActionPerformed

    //blast knop voor blastP
    //aantal alignments in de blast kan gekozen worden
    //TODO welke variabelen is de seq?
    private void blastPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastPActionPerformed
        // TODO add your handling code here:
        blastP(seq);
    }//GEN-LAST:event_blastPActionPerformed

    private void blastNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastNActionPerformed
        // TODO add your handling code here:
        blastN(seq);
    }//GEN-LAST:event_blastNActionPerformed

    
    private void B
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddGene;
    private javax.swing.JMenuItem AminoAcids;
    private javax.swing.JMenu Blast;
    private javax.swing.JMenuItem CDS;
    private javax.swing.JMenuItem CelType;
    private javax.swing.JMenuItem CorralationScores;
    private javax.swing.JMenuItem DNA;
    private javax.swing.JMenuItem Domein;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem EditSelectedFeature;
    private javax.swing.JMenu Export;
    private javax.swing.JMenu ExportTo;
    private javax.swing.JMenu ExtendsSelectedFeature;
    private javax.swing.JMenuItem FASTA;
    private javax.swing.JMenuItem Feature;
    private javax.swing.JLabel FeatureShow;
    private javax.swing.JScrollPane FeatureView;
    private javax.swing.JMenuItem Features;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem ForwardStrandOverview;
    private javax.swing.JMenuItem GFF;
    private javax.swing.JMenuItem Genbank;
    private javax.swing.JScrollPane GeneView;
    private javax.swing.JMenu Graph;
    private javax.swing.JMenuItem HeaderOfDefaultEntry;
    private javax.swing.JButton HelpButton;
    private javax.swing.JMenuItem ItemOpen;
    private javax.swing.JMenu NCBIsearches;
    private javax.swing.JMenuItem ORF;
    private javax.swing.JMenuItem Organism;
    private javax.swing.JMenuItem Overview;
    private javax.swing.JMenuItem Print;
    private javax.swing.JMenuItem PrintPreview;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem ReverseStrandOverview;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenu Search;
    private javax.swing.JMenuItem SelectedFeature;
    private javax.swing.JMenuItem SelectedFeatures;
    private javax.swing.JMenuItem SelectedSequence;
    private javax.swing.JTextField SequenceInfo;
    private javax.swing.JScrollPane SequenceView;
    private javax.swing.JMenuItem TblastN;
    private javax.swing.JMenuItem TblastX;
    private javax.swing.JMenuItem ToNextStopCodon;
    private javax.swing.JMenuItem ToPreviousStopCodon;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenu View;
    private javax.swing.JMenuItem agPercentage;
    private javax.swing.JMenuItem blastN;
    private javax.swing.JMenuItem blastP;
    private javax.swing.JMenuItem blastX;
    private javax.swing.JMenuItem gcFramePlot;
    private javax.swing.JMenuItem gcPercentage;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
